# RuboCop FactoryBot の設定ファイル
# 通常、基本設定ファイル (base.yml) と同時に利用する

plugins:
  - rubocop-factory_bot

########################################
# FactoryBot Cops: TODO
########################################
