# RuboCop Rails の設定ファイル
# 通常、基本設定ファイル (base.yml) と同時に利用する

plugins:
  - rubocop-rails

########################################
# Rails Cops: TODO
########################################

Rails:
  Enabled: true
