# RuboCop の基本設定ファイル

require: rubocop-performance

########################################
# Bundler Cops: Gemfile 用の設定
#   - RuboCop のデフォルト設定に従う
########################################


########################################
# Layout Cops: TODO
########################################


########################################
# Linting Cops: TODO
########################################

#
#
#   RuboCop Docs:
#


########################################
# Metrics Cops: TODO
########################################

#
#
#   RuboCop Docs:
#


########################################
# Migration Cops: TODO
########################################

#
#
#   RuboCop Docs:
#


########################################
# Naming Cops: TODO
########################################

#
#
#   RuboCop Docs:
#


########################################
# Performance Cops: TODO
########################################

#
#
#   RuboCop Docs:
#


########################################
# Security Cops: TODO
########################################

#
#
#   RuboCop Docs:
#


########################################
# Style Cops: TODO
########################################

#
#
#   RuboCop Docs:
#
Style/AsciiComments:
  Enabled: false

#
#
#   RuboCop Docs:
#
Style/Documentation:
  Enabled: false
