---
extends:
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings
  - prettier
  - plugin:prettier/recommended
plugins:
  - import
  - prettier
rules:
  'import/order':
    - error
    - newlines-between: always
  'import/no-default-export': error
  'import/no-deprecated': error
  'import/prefer-default-export': off
  'prettier/prettier':
    - error
    - arrowParens: avoid
      printWidth: 120
      singleQuote: true
      trailingComma: all
